/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GmoAozoraNetBankOpenApi);
  }
}(this, function(expect, GmoAozoraNetBankOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GmoAozoraNetBankOpenApi.Account();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Account', function() {
    it('should create an instance of Account', function() {
      // uncomment below and update the code to test Account
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be.a(GmoAozoraNetBankOpenApi.Account);
    });

    it('should have the property raId (base name: "raId")', function() {
      // uncomment below and update the code to test the property raId
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property raBranchCode (base name: "raBranchCode")', function() {
      // uncomment below and update the code to test the property raBranchCode
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property raBranchNameKana (base name: "raBranchNameKana")', function() {
      // uncomment below and update the code to test the property raBranchNameKana
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property raAccountNumber (base name: "raAccountNumber")', function() {
      // uncomment below and update the code to test the property raAccountNumber
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property raHolderName (base name: "raHolderName")', function() {
      // uncomment below and update the code to test the property raHolderName
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property baseDate (base name: "baseDate")', function() {
      // uncomment below and update the code to test the property baseDate
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

    it('should have the property baseTime (base name: "baseTime")', function() {
      // uncomment below and update the code to test the property baseTime
      //var instance = new GmoAozoraNetBankOpenApi.Account();
      //expect(instance).to.be();
    });

  });

}));
