/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GmoAozoraNetBankOpenApi);
  }
}(this, function(expect, GmoAozoraNetBankOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GmoAozoraNetBankOpenApi.VaTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VaTransaction', function() {
    it('should create an instance of VaTransaction', function() {
      // uncomment below and update the code to test VaTransaction
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be.a(GmoAozoraNetBankOpenApi.VaTransaction);
    });

    it('should have the property vaId (base name: "vaId")', function() {
      // uncomment below and update the code to test the property vaId
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property valueDate (base name: "valueDate")', function() {
      // uncomment below and update the code to test the property valueDate
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property vaBranchCode (base name: "vaBranchCode")', function() {
      // uncomment below and update the code to test the property vaBranchCode
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property vaBranchNameKana (base name: "vaBranchNameKana")', function() {
      // uncomment below and update the code to test the property vaBranchNameKana
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property vaAccountNumber (base name: "vaAccountNumber")', function() {
      // uncomment below and update the code to test the property vaAccountNumber
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property vaAccountNameKana (base name: "vaAccountNameKana")', function() {
      // uncomment below and update the code to test the property vaAccountNameKana
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property depositAmount (base name: "depositAmount")', function() {
      // uncomment below and update the code to test the property depositAmount
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property remitterNameKana (base name: "remitterNameKana")', function() {
      // uncomment below and update the code to test the property remitterNameKana
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property paymentBankName (base name: "paymentBankName")', function() {
      // uncomment below and update the code to test the property paymentBankName
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property paymentBranchName (base name: "paymentBranchName")', function() {
      // uncomment below and update the code to test the property paymentBranchName
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property partnerName (base name: "partnerName")', function() {
      // uncomment below and update the code to test the property partnerName
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property remarks (base name: "remarks")', function() {
      // uncomment below and update the code to test the property remarks
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

    it('should have the property itemKey (base name: "itemKey")', function() {
      // uncomment below and update the code to test the property itemKey
      //var instance = new GmoAozoraNetBankOpenApi.VaTransaction();
      //expect(instance).to.be();
    });

  });

}));
