/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GmoAozoraNetBankOpenApi) {
      root.GmoAozoraNetBankOpenApi = {};
    }
    root.GmoAozoraNetBankOpenApi.Account = factory(root.GmoAozoraNetBankOpenApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Account model module.
   * @module model/Account
   * @version 1.1.10
   */

  /**
   * Constructs a new <code>Account</code>.
   * 入金口座情報 
   * @alias module:model/Account
   * @class
   * @param raId {String} 入金口座ID 半角数字 入金先の口座を識別するID 
   * @param raBranchCode {String} 入金口座　支店コード 半角数字 
   * @param raBranchNameKana {String} 半角文字 
   * @param raAccountNumber {String} 半角数字 
   * @param raHolderName {String} 全角文字 
   * @param baseDate {String} 基準日 半角文字 応答日付、もしくは入金明細の基準日を示す。 YYYY-MM-DD形式 
   * @param baseTime {String} 基準時刻 半角文字 応答時刻、もしくは入金明細の基準時刻を示す。  ISO8601 時差(offset)も表記 HH:MM:SS+09:00形式 
   */
  var exports = function(raId, raBranchCode, raBranchNameKana, raAccountNumber, raHolderName, baseDate, baseTime) {
    var _this = this;

    _this['raId'] = raId;
    _this['raBranchCode'] = raBranchCode;
    _this['raBranchNameKana'] = raBranchNameKana;
    _this['raAccountNumber'] = raAccountNumber;
    _this['raHolderName'] = raHolderName;
    _this['baseDate'] = baseDate;
    _this['baseTime'] = baseTime;
  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Account} obj Optional instance to populate.
   * @return {module:model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('raId')) {
        obj['raId'] = ApiClient.convertToType(data['raId'], 'String');
      }
      if (data.hasOwnProperty('raBranchCode')) {
        obj['raBranchCode'] = ApiClient.convertToType(data['raBranchCode'], 'String');
      }
      if (data.hasOwnProperty('raBranchNameKana')) {
        obj['raBranchNameKana'] = ApiClient.convertToType(data['raBranchNameKana'], 'String');
      }
      if (data.hasOwnProperty('raAccountNumber')) {
        obj['raAccountNumber'] = ApiClient.convertToType(data['raAccountNumber'], 'String');
      }
      if (data.hasOwnProperty('raHolderName')) {
        obj['raHolderName'] = ApiClient.convertToType(data['raHolderName'], 'String');
      }
      if (data.hasOwnProperty('baseDate')) {
        obj['baseDate'] = ApiClient.convertToType(data['baseDate'], 'String');
      }
      if (data.hasOwnProperty('baseTime')) {
        obj['baseTime'] = ApiClient.convertToType(data['baseTime'], 'String');
      }
    }
    return obj;
  }

  /**
   * 入金口座ID 半角数字 入金先の口座を識別するID 
   * @member {String} raId
   */
  exports.prototype['raId'] = undefined;
  /**
   * 入金口座　支店コード 半角数字 
   * @member {String} raBranchCode
   */
  exports.prototype['raBranchCode'] = undefined;
  /**
   * 半角文字 
   * @member {String} raBranchNameKana
   */
  exports.prototype['raBranchNameKana'] = undefined;
  /**
   * 半角数字 
   * @member {String} raAccountNumber
   */
  exports.prototype['raAccountNumber'] = undefined;
  /**
   * 全角文字 
   * @member {String} raHolderName
   */
  exports.prototype['raHolderName'] = undefined;
  /**
   * 基準日 半角文字 応答日付、もしくは入金明細の基準日を示す。 YYYY-MM-DD形式 
   * @member {String} baseDate
   */
  exports.prototype['baseDate'] = undefined;
  /**
   * 基準時刻 半角文字 応答時刻、もしくは入金明細の基準時刻を示す。  ISO8601 時差(offset)も表記 HH:MM:SS+09:00形式 
   * @member {String} baseTime
   */
  exports.prototype['baseTime'] = undefined;



  return exports;
}));


