/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventType'));
  } else {
    // Browser globals (root is window)
    if (!root.GmoAozoraNetBankOpenApi) {
      root.GmoAozoraNetBankOpenApi = {};
    }
    root.GmoAozoraNetBankOpenApi.SubscribeRequestBody = factory(root.GmoAozoraNetBankOpenApi.ApiClient, root.GmoAozoraNetBankOpenApi.EventType);
  }
}(this, function(ApiClient, EventType) {
  'use strict';




  /**
   * The SubscribeRequestBody model module.
   * @module model/SubscribeRequestBody
   * @version 1.1.10
   */

  /**
   * Constructs a new <code>SubscribeRequestBody</code>.
   * @alias module:model/SubscribeRequestBody
   * @class
   * @param subscribeStatus {String} 配信状態 半角数字 0=配信停止要求 1=配信開始要求 
   * @param eventTypes {Array.<module:model/EventType>} イベント種別のリスト 
   */
  var exports = function(subscribeStatus, eventTypes) {
    var _this = this;

    _this['subscribeStatus'] = subscribeStatus;
    _this['eventTypes'] = eventTypes;
  };

  /**
   * Constructs a <code>SubscribeRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscribeRequestBody} obj Optional instance to populate.
   * @return {module:model/SubscribeRequestBody} The populated <code>SubscribeRequestBody</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('subscribeStatus')) {
        obj['subscribeStatus'] = ApiClient.convertToType(data['subscribeStatus'], 'String');
      }
      if (data.hasOwnProperty('eventTypes')) {
        obj['eventTypes'] = ApiClient.convertToType(data['eventTypes'], [EventType]);
      }
    }
    return obj;
  }

  /**
   * 配信状態 半角数字 0=配信停止要求 1=配信開始要求 
   * @member {String} subscribeStatus
   */
  exports.prototype['subscribeStatus'] = undefined;
  /**
   * イベント種別のリスト 
   * @member {Array.<module:model/EventType>} eventTypes
   */
  exports.prototype['eventTypes'] = undefined;



  return exports;
}));


