/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Account', 'model/VaTransaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Account'), require('./VaTransaction'));
  } else {
    // Browser globals (root is window)
    if (!root.GmoAozoraNetBankOpenApi) {
      root.GmoAozoraNetBankOpenApi = {};
    }
    root.GmoAozoraNetBankOpenApi.VaDepositTransactionMessage = factory(root.GmoAozoraNetBankOpenApi.ApiClient, root.GmoAozoraNetBankOpenApi.Account, root.GmoAozoraNetBankOpenApi.VaTransaction);
  }
}(this, function(ApiClient, Account, VaTransaction) {
  'use strict';




  /**
   * The VaDepositTransactionMessage model module.
   * @module model/VaDepositTransactionMessage
   * @version 1.1.10
   */

  /**
   * Constructs a new <code>VaDepositTransactionMessage</code>.
   * @alias module:model/VaDepositTransactionMessage
   * @class
   * @param messageId {String} メッセージID 半角英数字 メッセージを一意に識別するID 
   * @param timestamp {String} イベント生成日時 半角文字 ISO8601 時差(offset)も表記 YYYY-MM-DDTHH:MM:SS+09:00形式 
   * @param account {module:model/Account} 
   * @param vaTransaction {module:model/VaTransaction} 
   */
  var exports = function(messageId, timestamp, account, vaTransaction) {
    var _this = this;

    _this['messageId'] = messageId;
    _this['timestamp'] = timestamp;
    _this['account'] = account;
    _this['vaTransaction'] = vaTransaction;
  };

  /**
   * Constructs a <code>VaDepositTransactionMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VaDepositTransactionMessage} obj Optional instance to populate.
   * @return {module:model/VaDepositTransactionMessage} The populated <code>VaDepositTransactionMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messageId')) {
        obj['messageId'] = ApiClient.convertToType(data['messageId'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
      if (data.hasOwnProperty('account')) {
        obj['account'] = Account.constructFromObject(data['account']);
      }
      if (data.hasOwnProperty('vaTransaction')) {
        obj['vaTransaction'] = VaTransaction.constructFromObject(data['vaTransaction']);
      }
    }
    return obj;
  }

  /**
   * メッセージID 半角英数字 メッセージを一意に識別するID 
   * @member {String} messageId
   */
  exports.prototype['messageId'] = undefined;
  /**
   * イベント生成日時 半角文字 ISO8601 時差(offset)も表記 YYYY-MM-DDTHH:MM:SS+09:00形式 
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {module:model/Account} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {module:model/VaTransaction} vaTransaction
   */
  exports.prototype['vaTransaction'] = undefined;



  return exports;
}));


