/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VaDepositTransactionMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VaDepositTransactionMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.GmoAozoraNetBankOpenApi) {
      root.GmoAozoraNetBankOpenApi = {};
    }
    root.GmoAozoraNetBankOpenApi.VaDepositTransactionUnsentResponse = factory(root.GmoAozoraNetBankOpenApi.ApiClient, root.GmoAozoraNetBankOpenApi.VaDepositTransactionMessage);
  }
}(this, function(ApiClient, VaDepositTransactionMessage) {
  'use strict';




  /**
   * The VaDepositTransactionUnsentResponse model module.
   * @module model/VaDepositTransactionUnsentResponse
   * @version 1.1.10
   */

  /**
   * Constructs a new <code>VaDepositTransactionUnsentResponse</code>.
   * @alias module:model/VaDepositTransactionUnsentResponse
   * @class
   * @param messages {Array.<module:model/VaDepositTransactionMessage>} 
   */
  var exports = function(messages) {
    var _this = this;

    _this['messages'] = messages;
  };

  /**
   * Constructs a <code>VaDepositTransactionUnsentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VaDepositTransactionUnsentResponse} obj Optional instance to populate.
   * @return {module:model/VaDepositTransactionUnsentResponse} The populated <code>VaDepositTransactionUnsentResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messages')) {
        obj['messages'] = ApiClient.convertToType(data['messages'], [VaDepositTransactionMessage]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/VaDepositTransactionMessage>} messages
   */
  exports.prototype['messages'] = undefined;



  return exports;
}));


