/**
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse', 'model/SubscribeRequestBody', 'model/VaDepositTransactionUnsentResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/SubscribeRequestBody'), require('../model/VaDepositTransactionUnsentResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.GmoAozoraNetBankOpenApi) {
      root.GmoAozoraNetBankOpenApi = {};
    }
    root.GmoAozoraNetBankOpenApi.WebhooksApi = factory(root.GmoAozoraNetBankOpenApi.ApiClient, root.GmoAozoraNetBankOpenApi.ErrorResponse, root.GmoAozoraNetBankOpenApi.SubscribeRequestBody, root.GmoAozoraNetBankOpenApi.VaDepositTransactionUnsentResponse);
  }
}(this, function(ApiClient, ErrorResponse, SubscribeRequestBody, VaDepositTransactionUnsentResponse) {
  'use strict';

  /**
   * Webhooks service.
   * @module api/WebhooksApi
   * @version 1.1.10
   */

  /**
   * Constructs a new WebhooksApi. 
   * @alias module:api/WebhooksApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the accountsUsing operation.
     * @callback module:api/WebhooksApi~accountsUsingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 通知配信制御
     * 指定したイベント通知に対応するイベント通知（WebHook）の配信開始、配信停止をコントロールします
     * @param {String} authorization 認証情報 銀行システムが配信先システムに発行した、クライアントIDとクライアントシーレットを\&quot;:\&quot;（コロン）で連結し、Base64エンコードした値を設定 minLength: ‐ maxLength: ‐ 
     * @param {module:model/SubscribeRequestBody} body HTTPリクエストボディ
     * @param {module:api/WebhooksApi~accountsUsingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.accountsUsing = function(authorization, body, callback) {
      var postBody = body;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling accountsUsing");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling accountsUsing");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=UTF-8'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = null;

      return this.apiClient.callApi(
        '/subscribe', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountsUsingGET operation.
     * @callback module:api/WebhooksApi~accountsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VaDepositTransactionUnsentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 振込入金口座未送信明細取得
     * 配信停止状態となっている場合、本APIを利用することで未送信または送信エラーとなっている、振込入金口座の入金明細を一括で取得することができます 通常、未送信または送信エラーとなっている明細は配信再開後に通知されますが、本APIで取得された明細は配信済みとなるため、配信再開後には通知されません 未送信または送信エラーとなっている明細が無い場合は404 Not Foundを返却します &lt;p&gt;&lt;font color&#x3D;\&quot;red\&quot;&gt;※法人口座および個人事業主口座のみ対象となり、個人口座は対象外となります&lt;/font&gt;&lt;/p&gt; &lt;h4 style&#x3D;&#39;margin-top:30px; border-left: solid 4px #1B2F48; padding: 0.1em 0.5em; color:#1B2F48;&#39;&gt;詳細説明&lt;/h4&gt; &lt;div style&#x3D;&#39;margin:10px;&#39;&gt;   &lt;p style&#x3D;&#39;font-weight:bold; color:#616161;&#39;&gt;取得上限件数&lt;/p&gt;   &lt;p style&#x3D;&#39;padding-left:20px;&#39;&gt;500件&lt;/p&gt;   &lt;p style&#x3D;&#39;padding-left:20px;&#39;&gt;取得できる明細数が500に満たないときは取得できる明細のみを返却します&lt;/p&gt;   &lt;p style&#x3D;&#39;padding-left:20px;&#39;&gt;取得できた明細数が500件の場合、まだ取得できる明細が残っている可能性がありますので、&lt;/p&gt;   &lt;p style&#x3D;&#39;padding-left:20px;&#39;&gt;「404：Not Found」が返却されるまで、リクエストを繰り返してください。&lt;/p&gt; &lt;/div&gt; 
     * @param {String} authorization 認証情報 銀行システムが配信先システムに発行した、クライアントIDとクライアントシーレットを\&quot;:\&quot;（コロン）で連結し、Base64エンコードした値を設定 minLength: ‐ maxLength: ‐ 
     * @param {module:api/WebhooksApi~accountsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VaDepositTransactionUnsentResponse}
     */
    this.accountsUsingGET = function(authorization, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling accountsUsingGET");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json;charset=UTF-8'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = VaDepositTransactionUnsentResponse;

      return this.apiClient.callApi(
        '/unsentlist/va-deposit-transaction', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
